export const galleryPhotos = [
    {
        id:1,
        name:"1",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:2,
        name:"2",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:3,
        name:"3",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:4,
        name:"1",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:5,
        name:"2",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:6,
        name:"3",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:7,
        name:"1",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:8,
        name:"2",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:9,
        name:"3",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:10,
        name:"3",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:11,
        name:"1",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:12,
        name:"2",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:13,
        name:"3",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:14,
        name:"1",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:15,
        name:"2",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:16,
        name:"3",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:17,
        name:"1",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:18,
        name:"2",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:19,
        name:"3",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
    {
        id:20,
        name:"3",
        url:"/gallery/4tSalOk9wsk.jpg",
        description:"Описание",
        location:""
    },
]